[package]
name = "yapp"
version = "0.1.0"
authors = ["Aram Drevekenin <aram@poor.dev>"]
edition = "2018"

[dependencies]
indexmap = "2.9.0"
zellij-tile = "0.42.2"

[dev-dependencies]
insta = "1.43.1"
rstest = "0.25.0"
