[package]
name = "zellij-pane-picker"
version = "0.1.0"
authors = ["Shi Han NG <shihanng@gmail.com>"]
edition = "2018"

[dependencies]
indexmap = "2.9.0"
nucleo-matcher = "0.3.1"
thiserror = "2.0.12"
zellij-tile = "0.42.2"

[dev-dependencies]
insta = "1.43.1"
rstest = "0.25.0"
